# This project predicts the price of houses in Lagos

In [1]:
import pandas as pd

In [2]:
#Load csv files into dataframe
df1 = pd.read_csv("rent.csv")
df2 = pd.read_csv("sale.csv")

print("df1 type:", type(df1))
print("df1 shape:", df1.shape)
print()
print("df2 type:", type(df2))
print("df2 shape:", df2.shape)
print()

df1 type: <class 'pandas.core.frame.DataFrame'>
df1 shape: (9853, 4)

df2 type: <class 'pandas.core.frame.DataFrame'>
df2 shape: (9784, 4)

In [3]:
df1.head()

,Price,Pid,Property_name,Address
0,"400,000 / year",H1190,1 bedroom mini flat Flat / Apartment for rent ...,Fidiso Estate Abijo Ajah Lagos
1,"14,000,000 / year",G7398,3 bedroom Flat / Apartment for rent Gerrard Ge...,Gerrard Gerrard Gerard Road Ikoyi Lagos
2,"200,000 / year",H5843,1 bedroom mini flat Flat / Apartment for rent ...,Obadia Akoka Yaba Lagos
3,"800,000 / year",H1194,2 bedroom Flat / Apartment for rent Iju Ishaga...,surulere Iju Ishaga Road Gbaja Surulere Lagos
4,"300,000 / year",H5842,1 bedroom mini flat Flat / Apartment for rent ...,Close to Unilag Abule Oja Yaba Lagos

In [9]:
df1["Price"] = df1["Price"].str.replace("/ year", "").str.replace(",", "")
print("df1 type:", type(df1))
print("df1 shape:", df1.shape)
df1.head()

df1 type: <class 'pandas.core.frame.DataFrame'>
df1 shape: (9853, 4)

,Price,Pid,Property_name,Address
0,400000,H1190,1 bedroom mini flat Flat / Apartment for rent ...,Fidiso Estate Abijo Ajah Lagos
1,14000000,G7398,3 bedroom Flat / Apartment for rent Gerrard Ge...,Gerrard Gerrard Gerard Road Ikoyi Lagos
2,200000,H5843,1 bedroom mini flat Flat / Apartment for rent ...,Obadia Akoka Yaba Lagos
3,800000,H1194,2 bedroom Flat / Apartment for rent Iju Ishaga...,surulere Iju Ishaga Road Gbaja Surulere Lagos
4,300000,H5842,1 bedroom mini flat Flat / Apartment for rent ...,Close to Unilag Abule Oja Yaba Lagos

In [5]:
df1

,Price,Pid,Property_name,Address
0,"400,000 / year",H1190,1 bedroom mini flat Flat / Apartment for rent ...,Fidiso Estate Abijo Ajah Lagos
1,"14,000,000 / year",G7398,3 bedroom Flat / Apartment for rent Gerrard Ge...,Gerrard Gerrard Gerard Road Ikoyi Lagos
2,"200,000 / year",H5843,1 bedroom mini flat Flat / Apartment for rent ...,Obadia Akoka Yaba Lagos
3,"800,000 / year",H1194,2 bedroom Flat / Apartment for rent Iju Ishaga...,surulere Iju Ishaga Road Gbaja Surulere Lagos
4,"300,000 / year",H5842,1 bedroom mini flat Flat / Apartment for rent ...,Close to Unilag Abule Oja Yaba Lagos
...,...,...,...,...
9848,"400,000 / year",F1443,1 bedroom mini flat Flat / Apartment for rent ...,Alagomeji Alagomeji Yaba Lagos
9849,"800,000",F1442,3 bedroom Flat / Apartment for rent Onike Yaba...,iwaya road Onike Yaba Lagos
9850,"1,000,000 / year",F1441,2 bedroom Flat / Apartment for rent Adekunle Y...,Herbert Macaulay way Adekunle Yaba Lagos
9851,"1,500,000",F1433,3 bedroom Duplex for rent Off Chief Echegile S...,Off Chief Echegile Street Ogudu Orike Ogudu Lagos
9852,"4,000,000",F1430,8 bedroom Duplex for rent babs Animashuam Bode...,Census close babs Animashuam Bode Thomas Surul...

In [12]:
# Print df1 shape
data.shape
# Print df1 info
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9853 entries, 0 to 9852
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Price          9853 non-null   object
 1   Pid            9853 non-null   object
 2   Property_name  9853 non-null   object
 3   Address        9853 non-null   object
dtypes: object(4)
memory usage: 308.0+ KB

In [22]:
# check for missing values:
df1.isnull().sum()

Price            0
Pid              0
Property_name    0
Address          0
dtype: int64